receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  file:
    path: /data/traces.jsonl
    format: json

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
