package main

import (
	"bytes"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExtractSourceFields(t *testing.T) {
	// Create a temporary spec.go file for testing
	tempDir := t.TempDir()
	specFile := filepath.Join(tempDir, "spec.go")

	specContent := `package dalec

type Source struct {
	// Non-source fields
	Path string
	Includes []string
	
	// Source variant fields (should be detected)
	DockerImage *SourceDockerImage
	Git         *SourceGit
	HTTP        *SourceHTTP
	Context     *SourceContext
	Build       *SourceBuild
	Inline      *SourceInline
	
	// Other pointer fields (should be ignored)
	Generate []*SourceGenerator
	Other    *NonSourceType
}

type SourceDockerImage struct{}
type SourceGit struct{}
type SourceHTTP struct{}
type SourceContext struct{}
type SourceBuild struct{}
type SourceInline struct{}
type SourceGenerator struct{}
type NonSourceType struct{}
`

	err := os.WriteFile(specFile, []byte(specContent), 0644)
	assert.NoError(t, err)

	// Change to temp directory so the parser can find spec.go
	t.Chdir(tempDir)

	fields, err := extractSourceFields()
	assert.NoError(t, err)

	// Verify we found the expected source fields
	expectedFields := []SourceField{
		{Name: "Build", TypeName: "SourceBuild"},
		{Name: "Context", TypeName: "SourceContext"},
		{Name: "DockerImage", TypeName: "SourceDockerImage"},
		{Name: "Git", TypeName: "SourceGit"},
		{Name: "HTTP", TypeName: "SourceHTTP"},
		{Name: "Inline", TypeName: "SourceInline"},
	}

	assert.Equal(t, expectedFields, fields)
}

func TestExtractSourceFields_NoSourceStruct(t *testing.T) {
	tempDir := t.TempDir()
	specFile := filepath.Join(tempDir, "spec.go")

	specContent := `package dalec

type OtherStruct struct {
	Field string
}
`

	err := os.WriteFile(specFile, []byte(specContent), 0644)
	assert.NoError(t, err)

	t.Chdir(tempDir)

	fields, err := extractSourceFields()
	assert.NoError(t, err)
	assert.Equal(t, len(fields), 0)
}

func TestExtractSourceFields_InvalidGoFile(t *testing.T) {
	tempDir := t.TempDir()
	specFile := filepath.Join(tempDir, "spec.go")

	// Invalid Go syntax
	specContent := `package dalec

type Source struct {
	invalid syntax here
}
`

	err := os.WriteFile(specFile, []byte(specContent), 0644)
	assert.NoError(t, err)

	t.Chdir(tempDir)

	_, err = extractSourceFields()
	assert.True(t, err != nil)
	assert.Contains(t, err.Error(), "failed to parse")
}

func TestGenerateCode(t *testing.T) {
	fields := []SourceField{
		{Name: "Git", TypeName: "SourceGit"},
		{Name: "HTTP", TypeName: "SourceHTTP"},
		{Name: "DockerImage", TypeName: "SourceDockerImage"},
	}

	code, err := generateCode(fields)
	assert.NoError(t, err)

	// Verify the generated code is valid Go
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "", code, parser.ParseComments)
	assert.NoError(t, err)

	codeStr := string(code)

	// Check for expected function signatures
	assert.Contains(t, codeStr, "func (s *Source) validateSourceVariants() error")
	assert.Contains(t, codeStr, "func (s *Source) toInterface() source")

	// Check for package declaration and imports
	assert.Contains(t, codeStr, "package dalec")
	assert.Contains(t, codeStr, `import (`)
	assert.Contains(t, codeStr, `"fmt"`)

	// Check for generated comment
	assert.Contains(t, codeStr, "Code generated by cmd/gen-source-variants. DO NOT EDIT.")

	// Check that all fields are present in validation
	for _, field := range fields {
		expectedCheck := "if s." + field.Name + " != nil {"
		assert.Contains(t, codeStr, expectedCheck)
	}

	// Check that all fields are present in toInterface
	for _, field := range fields {
		expectedCase := "case s." + field.Name + " != nil:"
		expectedReturn := "return s." + field.Name
		assert.Contains(t, codeStr, expectedCase)
		assert.Contains(t, codeStr, expectedReturn)
	}

	// Check validation logic
	assert.Contains(t, codeStr, "count := 0")
	assert.Contains(t, codeStr, "count++")
	assert.Contains(t, codeStr, `return fmt.Errorf("no non-nil source variant")`)
	assert.Contains(t, codeStr, `return fmt.Errorf("more than one source variant defined")`)

	// Check toInterface logic
	assert.Contains(t, codeStr, "panic(errNoSourceVariant)")
}

func TestGenerateCode_EmptyFields(t *testing.T) {
	fields := []SourceField{}

	code, err := generateCode(fields)
	assert.NoError(t, err)

	// Verify the generated code is still valid Go
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "", code, parser.ParseComments)
	assert.NoError(t, err)

	codeStr := string(code)

	// Should still have the basic structure
	assert.Contains(t, codeStr, "func (s *Source) validateSourceVariants() error")
	assert.Contains(t, codeStr, "func (s *Source) toInterface() source")
	assert.Contains(t, codeStr, "count := 0")
}

func TestGenerateCode_SingleField(t *testing.T) {
	fields := []SourceField{
		{Name: "Git", TypeName: "SourceGit"},
	}

	code, err := generateCode(fields)
	assert.NoError(t, err)

	codeStr := string(code)

	// Check for the single field
	assert.Contains(t, codeStr, "if s.Git != nil {")
	assert.Contains(t, codeStr, "case s.Git != nil:")
	assert.Contains(t, codeStr, "return s.Git")
}

func TestGenerateCode_FormattingPreserved(t *testing.T) {
	fields := []SourceField{
		{Name: "Git", TypeName: "SourceGit"},
		{Name: "HTTP", TypeName: "SourceHTTP"},
	}

	code, err := generateCode(fields)
	assert.NoError(t, err)

	// Verify that the code is properly formatted by re-formatting it
	reformatted, err := format.Source(code)
	assert.NoError(t, err)

	// Should be identical since generateCode already formats
	assert.True(t, bytes.Equal(code, reformatted))
}

func TestMain_Integration(t *testing.T) {
	// This test verifies the main function works end-to-end
	tempDir := t.TempDir()

	// Create a spec.go file
	specFile := filepath.Join(tempDir, "spec.go")
	specContent := `package dalec

type Source struct {
	DockerImage *SourceDockerImage
	Git         *SourceGit
	HTTP        *SourceHTTP
}

type SourceDockerImage struct{}
type SourceGit struct{}
type SourceHTTP struct{}
`

	err := os.WriteFile(specFile, []byte(specContent), 0644)
	assert.NoError(t, err)

	t.Chdir(tempDir)

	// Set up args and call main
	outputFile := filepath.Join(tempDir, "generated.go")
	oldArgs := os.Args
	defer func() { os.Args = oldArgs }()

	os.Args = []string{"gen-source-variants", outputFile}

	// Capture any panics or exits
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("main() panicked: %v", r)
		}
	}()

	main()

	// Verify output file was created
	_, err = os.Stat(outputFile)
	assert.NoError(t, err)

	// Verify output file contents
	content, err := os.ReadFile(outputFile)
	assert.NoError(t, err)

	contentStr := string(content)
	assert.Contains(t, contentStr, "package dalec")
	assert.Contains(t, contentStr, "func (s *Source) validateSourceVariants() error")
	assert.Contains(t, contentStr, "func (s *Source) toInterface() source")

	// Verify it's valid Go
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "", content, parser.ParseComments)
	assert.NoError(t, err)
}

func TestMain_InvalidArgs(t *testing.T) {
	// We can't easily test os.Exit without subprocess testing
	// Instead, let's test the logic by checking what would happen with invalid args

	// Test that we get the expected behavior by checking args validation directly
	oldArgs := os.Args
	defer func() { os.Args = oldArgs }()

	// Test with no arguments - this would cause main to exit
	os.Args = []string{"gen-source-variants"}

	// We know from reading main() that it checks len(os.Args) != 2
	// Since we can't easily test os.Exit, we'll verify the condition
	assert.True(t, len(os.Args) != 2, "Invalid args should trigger exit condition")
}

func TestFieldSorting(t *testing.T) {
	// Test that fields are consistently sorted
	fields := []SourceField{
		{Name: "ZField", TypeName: "SourceZ"},
		{Name: "AField", TypeName: "SourceA"},
		{Name: "MField", TypeName: "SourceM"},
	}

	code, err := generateCode(fields)
	assert.NoError(t, err)

	codeStr := string(code)

	// Check that all fields are present
	assert.Contains(t, codeStr, "AField")
	assert.Contains(t, codeStr, "MField")
	assert.Contains(t, codeStr, "ZField")

	// Check that the validation logic contains all fields
	assert.Contains(t, codeStr, "if s.AField != nil {")
	assert.Contains(t, codeStr, "if s.MField != nil {")
	assert.Contains(t, codeStr, "if s.ZField != nil {")

	// Check that the toInterface logic contains all fields
	assert.Contains(t, codeStr, "case s.AField != nil:")
	assert.Contains(t, codeStr, "case s.MField != nil:")
	assert.Contains(t, codeStr, "case s.ZField != nil:")
}
